"""update attendance column

Revision ID: 65a93b3f7256
Revises: f508d2dc687d
Create Date: 2025-06-03 15:42:08.160977

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '65a93b3f7256'
down_revision = 'f508d2dc687d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendance_records', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=mysql.ENUM('present', 'late', 'absent', 'excused'),
               type_=sa.Enum('atvyko', 'pavėlavo', 'neatvyko', 'pateisinta', name='attendance_status'),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendance_records', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.Enum('atvyko', 'pavėlavo', 'neatvyko', 'pateisinta', name='attendance_status'),
               type_=mysql.ENUM('present', 'late', 'absent', 'excused'),
               existing_nullable=False)

    # ### end Alembic commands ###
