"""Add choice columns to test_questions

Revision ID: a375ede57814
Revises: 02c0ac682999
Create Date: 2025-06-03 18:03:24.442053

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a375ede57814'
down_revision = '02c0ac682999'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test_answers', schema=None) as batch_op:
        batch_op.alter_column('answer_text',
               existing_type=mysql.TEXT(),
               type_=sa.String(length=1),
               existing_nullable=False)

    with op.batch_alter_table('test_questions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('choice_a', sa.String(length=500), nullable=False))
        batch_op.add_column(sa.Column('choice_b', sa.String(length=500), nullable=False))
        batch_op.add_column(sa.Column('choice_c', sa.String(length=500), nullable=False))
        batch_op.add_column(sa.Column('choice_d', sa.String(length=500), nullable=False))
        batch_op.alter_column('position',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.alter_column('correct_answer',
               existing_type=mysql.TEXT(),
               type_=sa.String(length=1),
               nullable=False)
        batch_op.drop_column('question_type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test_questions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('question_type', mysql.ENUM('open', 'multiple_choice'), nullable=False))
        batch_op.alter_column('correct_answer',
               existing_type=sa.String(length=1),
               type_=mysql.TEXT(),
               nullable=True)
        batch_op.alter_column('position',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.drop_column('choice_d')
        batch_op.drop_column('choice_c')
        batch_op.drop_column('choice_b')
        batch_op.drop_column('choice_a')

    with op.batch_alter_table('test_answers', schema=None) as batch_op:
        batch_op.alter_column('answer_text',
               existing_type=sa.String(length=1),
               type_=mysql.TEXT(),
               existing_nullable=False)

    # ### end Alembic commands ###
