"""Add all models

Revision ID: a8c5e53e0251
Revises: 9c453e34496b
Create Date: 2025-05-26 15:16:56.158997

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a8c5e53e0251'
down_revision = '9c453e34496b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('faculties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('student_info', schema=None) as batch_op:
        batch_op.add_column(sa.Column('admission_year', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('current_semester', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('completed_credits', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('study_program_id', sa.Integer(), nullable=False))
        batch_op.alter_column('user_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.alter_column('group_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.drop_constraint(batch_op.f('student_info_ibfk_2'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'study_programs', ['study_program_id'], ['id'])
        batch_op.drop_column('program_id')

    with op.batch_alter_table('teacher_info', schema=None) as batch_op:
        batch_op.add_column(sa.Column('faculty_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'faculties', ['faculty_id'], ['id'])
        batch_op.drop_column('department')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_picture', sa.String(length=255), nullable=True))
        batch_op.drop_index(batch_op.f('username'))
        batch_op.drop_column('username')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', mysql.VARCHAR(length=64), nullable=False))
        batch_op.create_index(batch_op.f('username'), ['username'], unique=True)
        batch_op.drop_column('profile_picture')

    with op.batch_alter_table('teacher_info', schema=None) as batch_op:
        batch_op.add_column(sa.Column('department', mysql.VARCHAR(length=100), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('faculty_id')

    with op.batch_alter_table('student_info', schema=None) as batch_op:
        batch_op.add_column(sa.Column('program_id', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('student_info_ibfk_2'), 'study_programs', ['program_id'], ['id'])
        batch_op.alter_column('group_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.alter_column('user_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.drop_column('study_program_id')
        batch_op.drop_column('completed_credits')
        batch_op.drop_column('current_semester')
        batch_op.drop_column('admission_year')

    op.drop_table('faculties')
    # ### end Alembic commands ###
