# -*- coding: utf-8 -*-
# Alembic migration file

"""added faculty module

Revision ID: e87cbd61e204
Revises: a02419767a22
Create Date: 2025-05-28 11:32:53.876190

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e87cbd61e204'
down_revision = 'a02419767a22'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('faculties', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('faculties', schema=None) as batch_op:
        batch_op.drop_column('is_active')
        batch_op.drop_column('description')

    # ### end Alembic commands ###
