"""added group model

Revision ID: b7c23b494e10
Revises: a4c41c2e7d87
Create Date: 2025-05-27 14:59:38.157768

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b7c23b494e10'
down_revision = 'a4c41c2e7d87'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.add_column(sa.Column('admission_year', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('group_letter', sa.String(length=1), nullable=False))
        batch_op.add_column(sa.Column('study_program_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint(batch_op.f('groups_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'study_programs', ['study_program_id'], ['id'])
        batch_op.drop_column('program_id')

    with op.batch_alter_table('teacher_info', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('teacher_info_ibfk_2'), type_='foreignkey')
        batch_op.drop_column('faculty_id')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('failed_login_attempts', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('locked_until', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('locked_until')
        batch_op.drop_column('failed_login_attempts')

    with op.batch_alter_table('teacher_info', schema=None) as batch_op:
        batch_op.add_column(sa.Column('faculty_id', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('teacher_info_ibfk_2'), 'faculties', ['faculty_id'], ['id'])

    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.add_column(sa.Column('program_id', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('groups_ibfk_1'), 'study_programs', ['program_id'], ['id'])
        batch_op.drop_column('study_program_id')
        batch_op.drop_column('group_letter')
        batch_op.drop_column('admission_year')

    # ### end Alembic commands ###
