"""update teacher_info

Revision ID: 06473eb5f032
Revises: 1a77434b284e
Create Date: 2025-05-26 18:57:05.821481

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '06473eb5f032'
down_revision = '1a77434b284e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teacher_info', schema=None) as batch_op:
        batch_op.drop_column('department')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teacher_info', schema=None) as batch_op:
        batch_op.add_column(sa.Column('department', mysql.VARCHAR(length=100), nullable=True))

    # ### end Alembic commands ###
