"""added models

Revision ID: 16e8d4ab9a00
Revises: a8c5e53e0251
Create Date: 2025-05-27 08:21:07.203955

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '16e8d4ab9a00'
down_revision = 'a8c5e53e0251'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('study_programs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('code', sa.String(length=10), nullable=False))
        batch_op.add_column(sa.Column('faculty_id', sa.Integer(), nullable=True))
        batch_op.create_unique_constraint(None, ['code'])
        batch_op.create_foreign_key(None, 'faculties', ['faculty_id'], ['id'])
        batch_op.drop_column('faculty')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('study_programs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('faculty', mysql.VARCHAR(length=100), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('faculty_id')
        batch_op.drop_column('code')

    # ### end Alembic commands ###
