"""minor fixes everywhere

Revision ID: a02419767a22
Revises: e8addc8e45a5
Create Date: 2025-05-28 10:22:02.811724

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a02419767a22'
down_revision = 'e8addc8e45a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('modules', schema=None) as batch_op:
        batch_op.add_column(sa.Column('teacher_id', sa.Integer(), nullable=True))
        batch_op.alter_column('day_of_week',
               existing_type=mysql.VARCHAR(length=20),
               type_=sa.Enum('pirmadienis', 'antradienis', 'trečiadienis', 'ketvirtadienis', 'penktadienis'),
               nullable=False)
        batch_op.create_foreign_key(None, 'teacher_info', ['teacher_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('modules', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('day_of_week',
               existing_type=sa.Enum('pirmadienis', 'antradienis', 'trečiadienis', 'ketvirtadienis', 'penktadienis'),
               type_=mysql.VARCHAR(length=20),
               nullable=True)
        batch_op.drop_column('teacher_id')

    # ### end Alembic commands ###
