"""added module enrollment table with semester and prerequisite models

Revision ID: 0d7a26bb7fba
Revises: e87cbd61e204
Create Date: 2025-05-30 10:45:53.445518

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d7a26bb7fba'
down_revision = 'e87cbd61e204'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('module_prerequisites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('module_id', sa.Integer(), nullable=False),
    sa.Column('prerequisite_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['module_id'], ['modules.id'], ),
    sa.ForeignKeyConstraint(['prerequisite_id'], ['modules.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('module_id', 'prerequisite_id', name='unique_prerequisite')
    )
    with op.batch_alter_table('module_enrollments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.Enum('active', 'completed', 'failed', 'dropped'), nullable=True))
        batch_op.add_column(sa.Column('final_grade', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('completion_date', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('module_enrollments', schema=None) as batch_op:
        batch_op.drop_column('completion_date')
        batch_op.drop_column('final_grade')
        batch_op.drop_column('status')

    op.drop_table('module_prerequisites')
    # ### end Alembic commands ###
